name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install

      - name: Debug
        run: |
          pwd
          ls
          ls src
          ls src/public
          find . -name "marketplace.html"
      - name: Debug environment
        run: |
          node -v
          npx prettier --version
          echo "===== marketplace.html ====="
          nl -ba src/public/marketplace.html | sed -n '60,90p'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettier check
        run: npm run format-check

      - name: ESLint
        run: npm run lint

      - name: Jest tests
        run: npm test
